[project]
name = "langextract-mcp-server"
version = "1.0.0"
description = "MCP server for structured data extraction"
requires-python = ">=3.10"

dependencies = [
    "fastmcp>=0.1.0",
    "langextract>=1.0.0",
    "pydantic>=2.0.0",
]
